services:
  python:
    container_name: github_analysis
    build:
      dockerfile: ./.devcontainer/Dockerfile.github_analysis
      context: ../
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Europe/London
    volumes:
      - ../:/github_analysis/
    env_file:
      - ../.env
    tty: true
    extra_hosts:
      - "host.docker.internal:host-gateway"
