FROM python:3.12-bullseye

RUN apt-get update

RUN mkdir -p /github_analysis
WORKDIR /github_analysis

COPY ./requirements.txt /github_analysis/requirements.txt
RUN pip install --upgrade pip && pip install -r /github_analysis/requirements.txt

RUN pip install pylint==2.16.2 parameterized==0.9.0 pycodestyle==2.10.0 coverage==7.2.7

ENTRYPOINT ["bash"]